### ISSUE TITLE
sfu test error

### ISSUE THREAD

**Issue by xiaolingyi** [Jerc007/Open-GPGPU-FlexGrip-#2]
I found a potential bug when testing the exp function of the SFU module.  When the input is F23FF0D7, the output of RRO is FF80000, which finally leads to the final output of exp being 7F800000. The input is an extremely large negative number and the output is inf but the golden result is zero. So there is a potential error in RRO. There is a similar issue for E84059E3.

Could you please kindly check it? Thanks!
![wave exp out 1](https://github.com/Jerc007/Open-GPGPU-FlexGrip-/assets/43496629/b6427057-9651-4eaa-a7c3-c70701627ebf)
![wave exp rro out 1](https://github.com/Jerc007/Open-GPGPU-FlexGrip-/assets/43496629/7583a881-92fc-4a3e-ae46-b2e7e42d11e2)

**Comment by divadnauj-GB** [comment]
Thanks for noticing the error. Indeed the exceptions table for such operations was partially implemented. I have completed it and asked for a pull request, so the new update should fix the issue for the ex2 operation. The exceptions table implemented follows the CUDA-PTX ISA 1.4 specifications for IEEE754 single precision

| Input      | Result | 
| :---        |    :----:   |  
| (-inf, -128]     | +0.0       | 
| [+128, +inf]  | +inf        | 
|-Inf |+0.0|
|-subnormal |+1.0|
|-0.0 |+1.0|
|+0.0 |+1.0|
|+subnormal |+1.0|
|+Inf |+Inf|
|NaN |NaN|

**Comment by divadnauj-GB** [comment]
Thanks for noticing the error. Indeed the exceptions table for such operations was partially implemented. I have completed it and asked for a pull request, so the new update should fix the issue for the ex2 operation. The exceptions table implemented follows the CUDA-PTX ISA 1.4 specifications for IEEE754 single precision

| Input      | Result | 
| :---        |    :----:   |  
| (-inf, -128]     | +0.0       | 
| [+128, +inf]  | +inf        | 
|-Inf |+0.0|
|-subnormal |+1.0|
|-0.0 |+1.0|
|+0.0 |+1.0|
|+subnormal |+1.0|
|+Inf |+Inf|
|NaN |NaN|
